version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ../app:/app/app
      - ../config:/app/config
    networks:
      - vpa_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: vpa_db
      POSTGRES_USER: vpa_user
      POSTGRES_PASSWORD: vpa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vpa_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - vpa_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vpa_network

networks:
  vpa_network:
    driver: bridge

volumes:
  postgres_data: