api:
  # API Gateway Configuration
  host: "0.0.0.0"
  port: 8000
  debug: false

database:
  # Database Configuration
  sql:
    url: ${DATABASE_URL}
    pool_size: 5
    max_overflow: 10
  redis:
    url: ${REDIS_URL}
    db: 0

services:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: "gpt-4"
  google_vision:
    api_key: ${GOOGLE_VISION_API_KEY}

message_broker:
  rabbitmq:
    url: ${RABBITMQ_URL}
    exchange: "vpa_exchange"
    queue_prefix: "vpa_queue"

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    algorithm: ${JWT_ALGORITHM}
    access_token_expire: ${ACCESS_TOKEN_EXPIRE_MINUTES}